remote_theme: pages-themes/minimal@v0.2.0
title: Draft Statement on AI
description: "A draft statement on AI at SUNY Geneseo for discussion by the community. Contributors: Paul Schacht, Paul Jackson, Laurie Fox, Alexis Clifton, Matt Pastizzo, Dan DeZarn, Amy Sheldon, Melanie Blood, David Warden. Last updated 2025-02-21. Want to compare this version with earlier ones? Use the link below to track the changes on GitHub."
logo: "/images/cdl-blog-logo-33.png"